local dic = {}

dic.English_United_States = "English_United States"
dic.english = {
  ["Subject"] = "Subject",
  ["SubjectRequired"] = "Please enter the subject.",
  ["About"] = "About",
  ["Action"] = "Please select an option below:",
  ["Cancel"] = "Cancel",
  ["CancelRecord"] = "Cancel Record (F5)",
  ["Delete"] = "Delete",
  ["DeleteRecord"] = "Delete Record (F6)",
  ["Edit"] = "Edit",
  ["English"] = "English",
  ["Exit"] = "Exit",
  ["FirstRecord"] = "First Record",
  ["German"] = "German",
  ["Goto"] = "Goto",
  ["GotoRecord"] = "Goto Record (F2)",
  ["Help"] = "Help",
  ["LastRecord"] = "Last Record",
  ["New"] = "New",
  ["NewRecord"] = "New Record (F3)",
  ["NextRecord"] = "Next Record",
  ["OK"] = "OK",
  ["PreviousRecord"] = "Previous Record",
  ["Save"] = "Save",
  ["SaveRecord"] = "Save Record (F4)",
  ["Setup"] = "Setup",
  ["statustext"] = "  record %d of %d",
  ["Warning"] = "Warning",
  ["Options"] = {
    "create startmenu shortcut",
    "create desktop shortcut",
    "create file type association",
    "delete startmenu shortcut",
    "delete desktop shortcut",
    "delete file type association" },
}

dic.German_Germany = "German_Germany"
dic.german = {
  ["Subject"] = "Betreff",
  ["SubjectRequired"] = "Bitte geben Sie den Betreff ein.",
  ["About"] = "Info",
  ["Action"] = "Bitte wählen Sie eine der folgenden Optionen",
  ["Cancel"] = "Abbrechen",
  ["CancelRecord"] = "Datensatz abbrechen (F5)",
  ["Delete"] = "Löschen",
  ["DeleteRecord"] = "Datensatz löschen (F6)",
  ["Edit"] = "Bearbeiten",
  ["English"] = "Englisch",
  ["Exit"] = "Beenden",
  ["FirstRecord"] = "Erster Datensatz",
  ["German"] = "Deutsch",
  ["Goto"] = "Gehe zu",
  ["GotoRecord"] = "Gehe zu Datensatz (F2)",
  ["Help"] = "Hilfe",
  ["LastRecord"] = "Letzter Datensatz",
  ["New"] = "Neu",
  ["NewRecord"] = "Datensatz anlegen (F3)",
  ["NextRecord"] = "Nächster Datensatz",
  ["OK"] = "OK",
  ["PreviousRecord"] = "Vorheriger Datensatz",
  ["Save"] = "Speichern",
  ["SaveRecord"] = "Datensatz speichern (F4)",
  ["Setup"] = "Einrichten",
  ["statustext"] = "  Datensatz %d von %d",
  ["Warning"] = "Warnung",
  ["Options"] = {
    "Startmenü-Verknüpfung erstellen",
    "Desktop-Verknüpfung erstellen",
    "Dateityp-Zuordnung erstellen",
    "Startmenü-Verknüpfung löschen",
    "Desktop-Verknüpfung löschen",
    "Dateityp-Zuordnung löschen" },
}

return dic
