local dic = {}

dic.English_United_States = "English_United States"
dic.english = {
  ["About"] = "About",
  ["Action"] = "Please select an option below:",
  ["Cancel"] = "Cancel",
  ["CancelRecord"] = "Cancel Record",
  ["City"] = "City",
  ["Company"] = "Company",
  ["Country"] = "Country",
  ["Delete"] = "Delete",
  ["DeleteRecord"] = "Delete Record",
  ["Department"] = "Department",
  ["Edit"] = "Edit",
  ["English"] = "English",
  ["Exit"] = "Exit",
  ["FileTypeUnknown"] = "This file type is not supported.",
  ["FilterRecord"] = "Filter Record",
  ["FirstRecord"] = "First Record",
  ["FirtsName"] = "First Name",
  ["German"] = "German",
  ["Goto"] = "Goto",
  ["Help"] = "Help",
  ["LastName"] = "Last Name",
  ["LastNameRequired"] = "Please enter the last name.",
  ["LastRecord"] = "Last Record",
  ["MiddleName"] = "Middle Name",
  ["New"] = "New",
  ["NewRecord"] = "New Record",
  ["NextRecord"] = "Next Record",
  ["OK"] = "OK",
  ["PostalCode"] = "Postal Code",
  ["PreviousRecord"] = "Previous Record",
  ["Save"] = "Save",
  ["SaveRecord"] = "Save Record",
  ["Setup"] = "Setup",
  ["State"] = "State",
  ["statustext"] = "  record %d of %d",
  ["Street"] = "Street",
  ["Warning"] = "Warning",
  ["Options"] = {
    "create startmenu shortcut",
    "create desktop shortcut",
    "delete startmenu shortcut",
    "delete desktop shortcut" },
}

dic.German_Germany = "German_Germany"
dic.german = {
  ["About"] = "Info",
  ["Action"] = "Bitte wählen Sie eine der folgenden Optionen",
  ["Cancel"] = "Abbrechen",
  ["CancelRecord"] = "Datensatz abbrechen",
  ["City"] = "Ort",
  ["Company"] = "Firma",
  ["Country"] = "Land",
  ["Delete"] = "Löschen",
  ["DeleteRecord"] = "Datensatz löschen",
  ["Department"] = "Abteilung",
  ["Edit"] = "Bearbeiten",
  ["English"] = "Englisch",
  ["Exit"] = "Beenden",
  ["FileTypeUnknown"] = "Dieser Dateityp wird nicht unterstützt.",
  ["FilterRecord"] = "Datensatz filtern",
  ["FirstName"] = "Vorname",
  ["FirstRecord"] = "Erster Datensatz",
  ["German"] = "Deutsch",
  ["Goto"] = "Gehe zu",
  ["Help"] = "Hilfe",
  ["LastName"] = "Nachname",
  ["LastNameRequired"] = "Bitte geben Sie den Nachnamen ein.",
  ["LastRecord"] = "Letzter Datensatz",
  ["MiddleName"] = "Mittelname",
  ["New"] = "Neu",
  ["NewRecord"] = "Datensatz anlegen",
  ["NextRecord"] = "Nächster Datensatz",
  ["OK"] = "OK",
  ["PostalCode"] = "Postleitzahl",
  ["PreviousRecord"] = "Vorheriger Datensatz",
  ["Save"] = "Speichern",
  ["SaveRecord"] = "Datensatz speichern",
  ["Setup"] = "Einrichten",
  ["State"] = "Region",
  ["statustext"] = "  Datensatz %d von %d",
  ["Street"] = "Straße",
  ["Warning"] = "Warnung",
  ["Options"] = {
    "Startmenü-Verknüpfung erstellen",
    "Desktop-Verknüpfung erstellen",
    "Startmenü-Verknüpfung löschen",
    "Desktop-Verknüpfung löschen" },
}

return dic
